---
apiVersion: virtualization.deckhouse.io/v1alpha2
kind: ClusterVirtualImage
metadata:
  name: demo-alpine
spec:
  dataSource:
    type: ContainerImage
    containerImage:
      image: fl64/alpine-3-21-uefi-base:latest
