---
apiVersion: virtualization.deckhouse.io/v1alpha2
kind: ClusterVirtualImage
metadata:
  name: demo-alpine-3-23
spec:
  dataSource:
    type: ContainerImage
    containerImage:
      image: fl64/alpine-3-23-uefi-base:latest
